<a href="https://colab.research.google.com/github/harshinisathya09-star/projects-/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [ ]:
df = pd.read_csv("/content/diabetes.csv")

In [ ]:
def clean_data(df):
    df = df.drop_duplicates()
    df = df.fillna(df.median(numeric_only=True))
    return df

In [ ]:
def split_data(df):

    X = df.drop("Outcome", axis=1)

    y = df["Outcome"]

    X_train,X_test,y_train,y_test = train_test_split(
        X,y,test_size=0.2,random_state=42
    )

    scaler = StandardScaler()

    X_train = scaler.fit_transform(X_train)

    X_test = scaler.transform(X_test)

    return X_train,X_test,y_train,y_test

In [ ]:
def train_model(model,X_train,y_train):

    model.fit(X_train,y_train)

    return model

In [ ]:
def predict(model,X_test):

    return model.predict(X_test)

In [ ]:
def save_model(model,name):

    joblib.dump(model,name)

    print("Model Saved Successfully")

In [ ]:
import pandas as pd
df = pd.read_csv("/content/diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

In [ ]:
df = clean_data(df)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

In [ ]:
X_train, X_test, y_train, y_test = split_data(df)

In [ ]:
log_model = LogisticRegression()

train_model(log_model,X_train,y_train)

log_pred = predict(log_model,X_test)

In [ ]:
knn_model = KNeighborsClassifier()

train_model(knn_model,X_train,y_train)

knn_pred = predict(knn_model,X_test)

In [ ]:
tree_model = DecisionTreeClassifier(random_state=42)

train_model(tree_model,X_train,y_train)

tree_pred = predict(tree_model,X_test)

In [ ]:
models = {
    "Logistic Regression":log_pred,
    "KNN":knn_pred,
    "Decision Tree":tree_pred
}

for name,pred in models.items():

    print("\n",name)

    print("Accuracy:",accuracy_score(y_test,pred))

    print("Precision:",precision_score(y_test,pred))

    print("Recall:",recall_score(y_test,pred))

    print("F1 Score:",f1_score(y_test,pred))

    print("Confusion Matrix")

    print(confusion_matrix(y_test,pred))

 Logistic Regression
Accuracy: 0.7727272727272727
Precision: 0.6923076923076923
Recall: 0.6545454545454545
F1 Score: 0.6728971962616822
Confusion Matrix
[[83 16]
 [19 36]]

 KNN
Accuracy: 0.7987012987012987
Precision: 0.6935483870967742
Recall: 0.7818181818181819
F1 Score: 0.7350427350427351
Confusion Matrix
[[80 19]
 [12 43]]

 Decision Tree
Accuracy: 0.8441558441558441
Precision: 0.7627118644067796
Recall: 0.8181818181818182
F1 Score: 0.7894736842105263
Confusion Matrix
[[85 14]
 [10 45]]

In [ ]:
save_model(log_model,"diabetes_model.pkl")

Model Saved Successfully

In [ ]:
preg = int(input("Pregnancies: "))

glu = float(input("Glucose: "))

bp = float(input("Blood Pressure: "))

skin = float(input("Skin Thickness: "))

insulin = float(input("Insulin: "))

bmi = float(input("BMI: "))

dpf = float(input("Diabetes Pedigree Function: "))

age = int(input("Age: "))

Pregnancies: 2
Glucose: 140
Blood Pressure: 80
Skin Thickness: 30
Insulin: 100
BMI: 28
Diabetes Pedigree Function: 0.5
Age: 35

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

def split_data(df):

    X = df.drop("Outcome", axis=1)
    y = df["Outcome"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    scaler = StandardScaler()

    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    return X_train, X_test, y_train, y_test, scaler

In [ ]:
X_train, X_test, y_train, y_test, scaler = split_data(df)

In [ ]:
sample = [[preg, glu, bp, skin, insulin, bmi, dpf, age]]

sample = scaler.transform(sample)

prediction = log_model.predict(sample)

if prediction[0] == 1:
    print("Diabetic")
else:
    print("Not Diabetic")

Not Diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(